version: "3"
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    cap_add:
      - SYS_NICE
    container_name: csdl.db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: csdl
      MYSQL_USER: csdl
      MYSQL_PASSWORD: csdl

volumes:
  db:
    driver: local


